### ISSUE TITLE
Bug: Builds failing due to bcrypt

### ISSUE THREAD

**Issue by yamikuronue** [SockDrawer/SockRPG#161]
We can't seem to build docker containers anymore

```
Preparing build
[33mPrevious built image: r.cfcr.io/yamikuronue/sockdrawer/sockrpg@sha256:a4041eb6de34f5912f1d73c57dfa3527607987c4fabcdd9ced215c3ca07ae386 exists on the daemon and will be used as cache for the build[39m
Building image: sockdrawer/sockrpg:choreupdate-dependencies using unique hash: d8e5c4dc46fba3524d43efc25d9f039862cdbad3
Sending build context to Docker daemon  557.1kB
Sending build context to Docker daemon  3.342MB
Sending build context to Docker daemon  3.899MB
Sending build context to Docker daemon  5.014MB
Sending build context to Docker daemon  5.047MB


Step 1/15 : FROM node:8
8: Pulling from library/node
Digest: sha256:773480516f79e0948b02d7a06971b07bf76b08d706cf88a358b5b69dd4c83db0
Status: Image is up to date for node:8
 ---> 06f7c071f445
Step 2/15 : WORKDIR /opt/app
 ---> Using cache
 ---> b0963e0423a2
Step 3/15 : ENV NODE_ENV=production
 ---> Using cache
 ---> 9da782773b14
Step 4/15 : COPY package*.json /opt/app/
 ---> b67f8eaa0e74
Step 5/15 : RUN npm install
 ---> Running in 45586af927f5

> bcrypt@3.0.2 install /opt/app/node_modules/bcrypt
> node-pre-gyp install --fallback-to-build

[91mnode-pre-gyp[0m[91m [0m[91mWARN [0m[91mUsing needle for node-pre-gyp https download[0m[91m 
[0m[91mnode-pre-gyp WARN Pre-built binaries not installable for bcrypt@3.0.2 and node@8.14.0 (node-v57 ABI, glibc) (falling back to source compile with node-gyp)[0m[91m 
node-pre-gyp WARN Hit error Remote end closed socket abruptly. 
[0m[91mnode-pre-gyp[0m[91m WARN Pre-built binaries not installable for bcrypt@3.0.2 and node@8.14.0 (node-v57 ABI, glibc) (falling back to source compile with node-gyp) 
node-pre-gyp WARN Hit error bad download[0m[91m 
[0mmake: Entering directory '/opt/app/node_modules/bcrypt/build'
make: Entering directory '/opt/app/node_modules/bcrypt/build'
  CXX(target) Release/obj.target/bcrypt_lib/src/blowfish.o
  CXX(target) Release/obj.target/bcrypt_lib/src/blowfish.o
[91mrm: cannot remove './Release/.deps/Release/obj.target/bcrypt_lib/src/blowfish.o.d.raw': No such file or directory
[0mbcrypt_lib.target.mk:103: recipe for target 'Release/obj.target/bcrypt_lib/src/blowfish.o' failed
make: Leaving directory '/opt/app/node_modules/bcrypt/build'
[91mmake: *** [Release/obj.target/bcrypt_lib/src/blowfish.o] Error 1
[0m  CXX(target) Release/obj.target/bcrypt_lib/src/bcrypt.o
[91mgyp ERR! build error 
[0m[91mgyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/usr/local/lib/node_modules/npm/node_modules/node-gyp/lib/build.js:262:23)
gyp ERR! stack[0m[91m     at emitTwo (events.js:126:13)
gyp ERR! stack     at ChildProcess.emit (events.js:214:7)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:198:12)
[0m[91mgyp ERR! System Linux 4.15.0-1032-azure
[0m[91mgyp ERR! command "/usr/local/bin/node" "/usr/local/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "build" "--fallback-to-build" "--module=/opt/app/node_modules/bcrypt/lib/binding/bcrypt_lib.node" "--module_name=bcrypt_lib" "--module_path=/opt/app/node_modules/bcrypt/lib/binding" "--napi_version=3" "--node_abi_napi=napi" "--napi_build_version=0" "--node_napi_label=node-v57"
[0m[91mgyp ERR! cwd /opt/app/node_modules/bcrypt
gyp [0m[91mERR! node -v v8.14.0
gyp ERR! [0m[91mnode-gyp -v v3.8.0
gyp ERR! not ok 
[0m[91mnode-pre-gyp ERR! build error 
[0m[91mnode-pre-gyp ERR! stack Error: Failed to execute '/usr/local/bin/node /usr/local/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js build --fallback-to-build --module=/opt/app/node_modules/bcrypt/lib/binding/bcrypt_lib.node --module_name=bcrypt_lib --module_path=/opt/app/node_modules/bcrypt/lib/binding --napi_version=3 --node_abi_napi=napi --napi_build_version=0 --node_napi_label=node-v57' (1)
node-pre-gyp[0m[91m ERR! stack     at ChildProcess.<anonymous> (/opt/app/node_modules/bcrypt/node_modules/node-pre-gyp/lib/util/compile.js:83:29)
[0m[91mnode-pre-gyp[0m[91m ERR! [0m[91mstack     at emitTwo (events.js:126:13)
node-pre-gyp ERR! [0m[91mstack     at ChildProcess.emit (events.js:214:7)
node-pre-gyp ERR! stack     at maybeClose (internal/child_process.js:915:16)
node-pre-gyp[0m[91m ERR![0m[91m stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:209:5)
[0m[91mnode-pre-gyp ERR! System Linux 4.15.0-1032-azure
[0m[91mnode-pre-gyp ERR! command "/usr/local/bin/node" "/opt/app/node_modules/bcrypt/node_modules/.bin/node-pre-gyp" "install" "--fallback-to-build"
[0m[91mnode-pre-gyp ERR! cwd /opt/app/node_modules/bcrypt
[0m[91mnode-pre-gyp ERR! node -v v8.14.0
[0m[91mnode-pre-gyp ERR! node-pre-gyp -v v0.11.0
node-pre-gyp ERR! [0m[91mnot ok 
[0mFailed to execute '/usr/local/bin/node /usr/local/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js build --fallback-to-build --module=/opt/app/node_modules/bcrypt/lib/binding/bcrypt_lib.node --module_name=bcrypt_lib --module_path=/opt/app/node_modules/bcrypt/lib/binding --napi_version=3 --node_abi_napi=napi --napi_build_version=0 --node_napi_label=node-v57' (1)
[91m../src/bcrypt.cc:38:22: fatal error: node_blf.h: No such file or directory
compilation terminated.
[0mbcrypt_lib.target.mk:103: recipe for target 'Release/obj.target/bcrypt_lib/src/bcrypt.o' failed
make: Leaving directory '/opt/app/node_modules/bcrypt/build'
[91mmake: *** [Release/obj.target/bcrypt_lib/src/bcrypt.o] Error 1
[0m[91mgyp[0m[91m [0m[91mERR! build error[0m[91m 
[0m[91mgyp [0m[91mERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack[0m[91m     at ChildProcess.onExit (/usr/local/lib/node_modules/npm/node_modules/node-gyp/lib/build.js:262:23)
gyp ERR! stack     at emitTwo (events.js:126:13)
gyp ERR! stack     at ChildProcess.emit (events.js:214:7)
gyp [0m[91mERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:198:12)
[0m[91mgyp ERR! [0m[91mSystem Linux 4.15.0-1032-azure
[0m[91mgyp ERR! command[0m[91m "/usr/local/bin/node" "/usr/local/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "build" "--fallback-to-build" "--module=/opt/app/node_modules/bcrypt/lib/binding/bcrypt_lib.node" "--module_name=bcrypt_lib" "--module_path=/opt/app/node_modules/bcrypt/lib/binding" "--napi_version=3" "--node_abi_napi=napi" "--napi_build_version=0" "--node_napi_label=node-v57"
gyp ERR! [0m[91mcwd /opt/app/node_modules/bcrypt
gyp ERR! node -v v8.14.0
[0m[91mgyp ERR! node-gyp -v v3.8.0
gyp[0m[91m ERR! not ok 
[0m[91mnpm ERR! code[0m[91m ELIFECYCLE
[0m[91mnpm ERR! [0m[91merrno[0m[91m 1
[0m[91mnpm ERR! bcrypt@3.0.2 install: `node-pre-gyp install --fallback-to-build`
npm[0m[91m ERR![0m[91m Exit status 1
npm ERR! 
npm [0m[91mERR![0m[91m Failed at the bcrypt@3.0.2 install script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
[0m[91m
[0m[91mnpm ERR![0m[91m A complete log of this run can be found in:
npm [0m[91mERR!     /root/.npm/_logs/2018-11-30T01_07_11_767Z-debug.log
[0mRemoving intermediate container 45586af927f5
[31m[1mThe command '/bin/sh -c npm install' returned a non-zero code: 1
[22m[39m[31m[SYSTEM] Error: Failed to build image: r.cfcr.io/yamikuronue/sockdrawer/sockrpg:d8e5c4dc46fba3524d43efc25d9f039862cdbad3; caused by NonZeroExitCodeError: Container for step title: Building Docker Image, step type: build, operation: Building image failed with exit code: 1[0m
                                               
```

**Comment by AccaliaDeElementia** [comment]
Fixed by #166
